apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: toolhive-registry-api-rolebinding
  labels:
    app.kubernetes.io/name: toolhive-registry-api
    app.kubernetes.io/component: registry-api
    app.kubernetes.io/managed-by: toolhive-operator
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: toolhive-registry-api-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.registryAPI.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
