apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
  name: toolhive-registry-api-role
  labels:
    app.kubernetes.io/name: toolhive-registry-api
    app.kubernetes.io/component: registry-api
    app.kubernetes.io/managed-by: toolhive-operator
rules:
- apiGroups:
  - toolhive.stacklok.dev
  resources:
  - mcpservers
  verbs:
  - get
  - list
  - watch
