operator:
  image: ko.local/thv-operator:ci-test
  toolhiveRunnerImage: ko.local/thv-proxyrunner:ci-test
  vmcpImage: ko.local/vmcp:ci-test
  env:
  - name: TEST_ENV_VAR
    value: "my-test-env-var"
  - name: ANOTHER_TEST_ENV_VAR
    value: "another-test-env-var"
