operator:
  image: ko.local/thv-operator:ci-test
  toolhiveRunnerImage: ko.local/thv-proxyrunner:ci-test
  vmcpImage: ko.local/vmcp:ci-test
  extraVolumeMounts:
    - name: test
      mountPath: /somepath
      readOnly: true
  extraVolumes:
    - name: test
      emptyDir:
        sizeLimit: 5Mi
