name: Operator CI

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  operator-tests:
    name: Operator Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.44.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: task operator-test

  operator-tests-integration:
    name: Operator Tests Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.44.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: task operator-test-integration

  build-operator:
    name: Build Operator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.44.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build operator
        run: task build-operator

  generate-crds:
    name: Generate CRDs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.44.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate CRDs
        run: task operator-manifests

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code deploy/charts/operator-crds/templates || echo "crd-changes=true" >> $GITHUB_OUTPUT
          git diff --exit-code deploy/charts/operator/templates || echo "operator-changes=true" >> $GITHUB_OUTPUT

      - name: Fail if CRDs are not up to date
        if: steps.git-check.outputs.crd-changes == 'true' || steps.git-check.outputs.operator-changes == 'true'
        run: |
          echo "CRDs are not up to date. Please run 'task operator-manifests' and commit the changes."
          exit 1

  generate-crd-docs:
    name: Generate CRD Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.44.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate CRD Docs
        run: task crdref-gen
        working-directory: cmd/thv-operator

      - name: Check for changes
        id: git-docs-check
        run: |
          git diff --exit-code -- docs/operator/crd-api.md || echo "crd-changes=true" >> $GITHUB_OUTPUT

      - name: Fail if CRDs are not up to date
        if: steps.git-docs-check.outputs.crd-changes == 'true'
        run: |
          echo "Docs for CRDs are not up to date. Please run 'task crdref-gen' and commit the changes."
          exit 1

  e2e-tests-operator:
    name: E2E Tests Operator
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        # Before someone says it, yes we could just put the number here and not the full image name,
        # but we want to make sure renovate bumps the versions when new ones are released. Doing that with
        # just the number is a bit more difficult and i like simple things.
        version: [
          "kindest/node:v1.33.7",
          "kindest/node:v1.34.3",
          "kindest/node:v1.35.1"
        ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      
    - name: Set up Helm
      uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1 # pin@v4.3.0

    - name: Setup Ko
      uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9

    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
      with:
        go-version-file: 'go.mod'
        cache: true
        
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.44.1
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install yardstick client
      run: |
        go install github.com/stackloklabs/yardstick/cmd/yardstick-client@v0.0.2
        
    - name: Install Chainsaw
      uses: kyverno/action-install-chainsaw@06560d18422209e9c1e08e931d477d04bf2674c1 # v0.2.14
      with:
        release: v0.2.12

    - name: Create KIND Cluster
      uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # pin@v1.12.0
      with:
        cluster_name: toolhive
        version: v0.29.0
        cloud_provider: true
        node_image: ${{ matrix.version }}

    - name: Run Chainsaw tests
      run: |
        kind get kubeconfig --name toolhive > kconfig.yaml
        export KUBECONFIG=kconfig.yaml
        chainsaw test --test-dir test/e2e/chainsaw/operator/multi-tenancy/setup --config .chainsaw.yaml
        chainsaw test --test-dir test/e2e/chainsaw/operator/multi-tenancy/test-scenarios --config .chainsaw.yaml
        chainsaw test --test-dir test/e2e/chainsaw/operator/multi-tenancy/cleanup --config .chainsaw.yaml
        chainsaw test --test-dir test/e2e/chainsaw/operator/single-tenancy/setup --config .chainsaw.yaml
        chainsaw test --test-dir test/e2e/chainsaw/operator/single-tenancy/test-scenarios --parallel 10 --config .chainsaw.yaml
        chainsaw test --test-dir test/e2e/chainsaw/operator/single-tenancy/cleanup --config .chainsaw.yaml
