name: Docgen

on:
  workflow_call:

jobs:
  verify-swagger-docs:
    name: Verify Swagger Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: go.mod
      - name: Install swag
        run: go install github.com/swaggo/swag/v2/cmd/swag@latest
      - run: ./cmd/help/verify.sh
