name: Docgen

on:
  workflow_call:

jobs:
  verify-swagger-docs:
    name: Verify Swagger Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: go.mod
      - name: Install swag
        run: go install github.com/swaggo/swag/v2/cmd/swag@latest
      - run: ./cmd/help/verify.sh
